# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feyzi/streaming-udp-video

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feyzi/streaming-udp-video

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feyzi/streaming-udp-video/CMakeFiles /home/feyzi/streaming-udp-video/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feyzi/streaming-udp-video/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sender

# Build rule for target.
Sender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sender
.PHONY : Sender

# fast build rule for target.
Sender/fast:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/build
.PHONY : Sender/fast

#=============================================================================
# Target rules for targets named Receiver

# Build rule for target.
Receiver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Receiver
.PHONY : Receiver

# fast build rule for target.
Receiver/fast:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/build
.PHONY : Receiver/fast

src/protocols/basic_protocol.o: src/protocols/basic_protocol.cpp.o

.PHONY : src/protocols/basic_protocol.o

# target to build an object file
src/protocols/basic_protocol.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/protocols/basic_protocol.cpp.o
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/protocols/basic_protocol.cpp.o
.PHONY : src/protocols/basic_protocol.cpp.o

src/protocols/basic_protocol.i: src/protocols/basic_protocol.cpp.i

.PHONY : src/protocols/basic_protocol.i

# target to preprocess a source file
src/protocols/basic_protocol.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/protocols/basic_protocol.cpp.i
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/protocols/basic_protocol.cpp.i
.PHONY : src/protocols/basic_protocol.cpp.i

src/protocols/basic_protocol.s: src/protocols/basic_protocol.cpp.s

.PHONY : src/protocols/basic_protocol.s

# target to generate assembly for a file
src/protocols/basic_protocol.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/protocols/basic_protocol.cpp.s
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/protocols/basic_protocol.cpp.s
.PHONY : src/protocols/basic_protocol.cpp.s

src/receiver.o: src/receiver.cpp.o

.PHONY : src/receiver.o

# target to build an object file
src/receiver.cpp.o:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver.cpp.o
.PHONY : src/receiver.cpp.o

src/receiver.i: src/receiver.cpp.i

.PHONY : src/receiver.i

# target to preprocess a source file
src/receiver.cpp.i:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver.cpp.i
.PHONY : src/receiver.cpp.i

src/receiver.s: src/receiver.cpp.s

.PHONY : src/receiver.s

# target to generate assembly for a file
src/receiver.cpp.s:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver.cpp.s
.PHONY : src/receiver.cpp.s

src/receiver/receiver_socket.o: src/receiver/receiver_socket.cpp.o

.PHONY : src/receiver/receiver_socket.o

# target to build an object file
src/receiver/receiver_socket.cpp.o:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver/receiver_socket.cpp.o
.PHONY : src/receiver/receiver_socket.cpp.o

src/receiver/receiver_socket.i: src/receiver/receiver_socket.cpp.i

.PHONY : src/receiver/receiver_socket.i

# target to preprocess a source file
src/receiver/receiver_socket.cpp.i:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver/receiver_socket.cpp.i
.PHONY : src/receiver/receiver_socket.cpp.i

src/receiver/receiver_socket.s: src/receiver/receiver_socket.cpp.s

.PHONY : src/receiver/receiver_socket.s

# target to generate assembly for a file
src/receiver/receiver_socket.cpp.s:
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/receiver/receiver_socket.cpp.s
.PHONY : src/receiver/receiver_socket.cpp.s

src/sender.o: src/sender.cpp.o

.PHONY : src/sender.o

# target to build an object file
src/sender.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender.cpp.o
.PHONY : src/sender.cpp.o

src/sender.i: src/sender.cpp.i

.PHONY : src/sender.i

# target to preprocess a source file
src/sender.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender.cpp.i
.PHONY : src/sender.cpp.i

src/sender.s: src/sender.cpp.s

.PHONY : src/sender.s

# target to generate assembly for a file
src/sender.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender.cpp.s
.PHONY : src/sender.cpp.s

src/sender/sender_socket.o: src/sender/sender_socket.cpp.o

.PHONY : src/sender/sender_socket.o

# target to build an object file
src/sender/sender_socket.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender/sender_socket.cpp.o
.PHONY : src/sender/sender_socket.cpp.o

src/sender/sender_socket.i: src/sender/sender_socket.cpp.i

.PHONY : src/sender/sender_socket.i

# target to preprocess a source file
src/sender/sender_socket.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender/sender_socket.cpp.i
.PHONY : src/sender/sender_socket.cpp.i

src/sender/sender_socket.s: src/sender/sender_socket.cpp.s

.PHONY : src/sender/sender_socket.s

# target to generate assembly for a file
src/sender/sender_socket.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/sender/sender_socket.cpp.s
.PHONY : src/sender/sender_socket.cpp.s

src/util/util.o: src/util/util.cpp.o

.PHONY : src/util/util.o

# target to build an object file
src/util/util.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/util/util.cpp.o
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/util/util.cpp.o
.PHONY : src/util/util.cpp.o

src/util/util.i: src/util/util.cpp.i

.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/util/util.cpp.i
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/util/util.cpp.i
.PHONY : src/util/util.cpp.i

src/util/util.s: src/util/util.cpp.s

.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/util/util.cpp.s
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/util/util.cpp.s
.PHONY : src/util/util.cpp.s

src/video/video_capture.o: src/video/video_capture.cpp.o

.PHONY : src/video/video_capture.o

# target to build an object file
src/video/video_capture.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_capture.cpp.o
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_capture.cpp.o
.PHONY : src/video/video_capture.cpp.o

src/video/video_capture.i: src/video/video_capture.cpp.i

.PHONY : src/video/video_capture.i

# target to preprocess a source file
src/video/video_capture.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_capture.cpp.i
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_capture.cpp.i
.PHONY : src/video/video_capture.cpp.i

src/video/video_capture.s: src/video/video_capture.cpp.s

.PHONY : src/video/video_capture.s

# target to generate assembly for a file
src/video/video_capture.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_capture.cpp.s
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_capture.cpp.s
.PHONY : src/video/video_capture.cpp.s

src/video/video_frame.o: src/video/video_frame.cpp.o

.PHONY : src/video/video_frame.o

# target to build an object file
src/video/video_frame.cpp.o:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_frame.cpp.o
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_frame.cpp.o
.PHONY : src/video/video_frame.cpp.o

src/video/video_frame.i: src/video/video_frame.cpp.i

.PHONY : src/video/video_frame.i

# target to preprocess a source file
src/video/video_frame.cpp.i:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_frame.cpp.i
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_frame.cpp.i
.PHONY : src/video/video_frame.cpp.i

src/video/video_frame.s: src/video/video_frame.cpp.s

.PHONY : src/video/video_frame.s

# target to generate assembly for a file
src/video/video_frame.cpp.s:
	$(MAKE) -f CMakeFiles/Sender.dir/build.make CMakeFiles/Sender.dir/src/video/video_frame.cpp.s
	$(MAKE) -f CMakeFiles/Receiver.dir/build.make CMakeFiles/Receiver.dir/src/video/video_frame.cpp.s
.PHONY : src/video/video_frame.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Sender"
	@echo "... Receiver"
	@echo "... src/protocols/basic_protocol.o"
	@echo "... src/protocols/basic_protocol.i"
	@echo "... src/protocols/basic_protocol.s"
	@echo "... src/receiver.o"
	@echo "... src/receiver.i"
	@echo "... src/receiver.s"
	@echo "... src/receiver/receiver_socket.o"
	@echo "... src/receiver/receiver_socket.i"
	@echo "... src/receiver/receiver_socket.s"
	@echo "... src/sender.o"
	@echo "... src/sender.i"
	@echo "... src/sender.s"
	@echo "... src/sender/sender_socket.o"
	@echo "... src/sender/sender_socket.i"
	@echo "... src/sender/sender_socket.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
	@echo "... src/video/video_capture.o"
	@echo "... src/video/video_capture.i"
	@echo "... src/video/video_capture.s"
	@echo "... src/video/video_frame.o"
	@echo "... src/video/video_frame.i"
	@echo "... src/video/video_frame.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

